repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
        exclude: '\.svg'
  - repo: local
    hooks:
      - id: check-test-file-name
        name: check test file name convention
        entry: python tools/check-test-file-name.py
        language: python
        files: '(tests/.*\.py)$'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude_types:
          - svg
